# Generated by Django 3.1.2 on 2020-10-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sightings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(help_text='Latitude')),
                ('Longitude', models.FloatField(help_text='Longitude')),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel ID', max_length=20)),
                ('Shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], max_length=2)),
                ('Date', models.DateField(help_text='Date')),
                ('Age', models.CharField(choices=[('adult', 'adult'), ('juvenile', 'juvenile'), ('other', 'other')], max_length=10)),
                ('Primary_Fur_Color', models.CharField(choices=[('gray', 'gray'), ('cinnamon', 'cinnamon'), ('black', 'black'), ('other', 'other')], default='other', help_text='Primary Fur Color', max_length=20)),
                ('Location', models.CharField(choices=[('ground plane', 'ground plane'), ('above ground', 'above ground'), ('other', 'other')], default='other', max_length=20)),
                ('Specific_location', models.CharField(help_text='Specific location', max_length=200)),
                ('Running', models.BooleanField(default=False)),
                ('Chasing', models.BooleanField(default=False)),
                ('Climbing', models.BooleanField(default=False)),
                ('Eating', models.BooleanField(default=False)),
                ('Foraging', models.BooleanField(default=False)),
                ('Other_Activities', models.CharField(max_length=200)),
                ('Kuks', models.BooleanField(default=False)),
                ('Quaas', models.BooleanField(default=False)),
                ('Moans', models.BooleanField(default=False)),
                ('Tail_flags', models.BooleanField(default=False)),
                ('Tail_twitches', models.BooleanField(default=False)),
                ('Approaches', models.BooleanField(default=False)),
                ('Indifferent', models.BooleanField(default=False)),
                ('Runs_from', models.BooleanField(default=False)),
            ],
        ),
    ]
